# Generated by Django 5.1.3 on 2024-11-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jb_goal_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goals',
            name='due_date',
        ),
        migrations.AddField(
            model_name='goals',
            name='duration',
            field=models.CharField(choices=[('emp', ''), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='emp', max_length=60),
        ),
    ]
